# LazyDocker Custom Configuration Example
# Place this file in ~/.dotfiles/lazydocker/config.yml
gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
    returnImmediately: false

commandTemplates:
  dockerCompose: "docker compose"
  dockerComposeServiceLogs: "docker compose logs --follow {{ .Service.Name }}"

logs:
  since: "10m"
